pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  setup:
    image: node:11
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn

  build:
    image: node:11
    group: testing
    secrets:
      - source: auth_callback
        target: REACT_APP_AUTH_CALLBACK
      - source: auth_client_id
        target: REACT_APP_AUTH_CLIENT_ID
      - source: auth_endpoint
        target: REACT_APP_AUTH_ENDPOINT
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn build

  test:
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      yarn test

  compile-typescript:
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn run tsc

  lint-typescript:
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-ts

  lint-prettier:
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-prettier

  rebuild-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  
  deploy:
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
      status: success
    bucket: receipt-form-prod
    source: build/**/*
    target: /
    strip_prefix: build/
    acl: public-read
    region: eu-west-1
