kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  - name: setup
    image: node:11
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn

  - name: build
    image: node:11
    group: testing
    secrets:
      - source: auth_callback
        target: REACT_APP_AUTH_CALLBACK
      - source: auth_client_id
        target: REACT_APP_AUTH_CLIENT_ID
      - source: auth_endpoint
        target: REACT_APP_AUTH_ENDPOINT
      - source: sentry_dsn
        target: REACT_APP_SENTRY_DSN
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn build

  - name: build-lambda
    image: node:11
    group: testing
    secrets:
      - source: sentry_dsn
        target: SENTRY_DSN
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn build:lambda

  - name: test
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      yarn test

  - name: compile-typescript
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn run tsc

  - name: lint-typescript
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-ts

  - name: lint-prettier
    image: node:11
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-prettier

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  
  - name: deploy-frontend
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
      status: success
    settings:
      bucket: receipt-form-prod
      source: build/**/*
      target: /
      strip_prefix: build/
      acl: public-read
      region: eu-west-1

  - name: deploy-lambda
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
      status: success
    settings:
      bucket: receipt-form-lambda
      source: /**/*
      target: /
      region: eu-west-1
      exclude:
        - "build/*"
        - "*.ts*"
        - "*.tsx*"
        - "*.map*"
        - "*.lock*"
        - "*.git*"
        - "*.css*"
        - "*.scss*"
        - "*.html*"
        - "*.png*"
        - "*.md*"
        - "*LICENSE*"
        - "*.xml*"
        - "*.idea*"
        - "*package-lock.json*"
