FROM node:12-alpine

LABEL maintainer="dotkom@online.ntnu.no"
LABEL project="receipt-form"

ARG SENTRY_DNS=''

ENV WORKDIR=/srv/app
ENV NODE_ENV=production

WORKDIR ${WORKDIR}

# Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn

# Copy project files
COPY . .

# Build backend
RUN yarn build:lambda

EXPOSE 8081

CMD ["node", "./src/lambda/index.js"]
