name: Push
on:
  push:

jobs:
  lint-test:
    if: "!contains(github.event.head_commit.message, '[skip:ci]')"
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Typescript compile
        run: yarn tsc

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Eslint
          eslint: true
          eslint_dir: src/
          eslint_extensions: js,jsx,ts,tsx
          # Prettier
          prettier: true
          prettier_dir: src/

      - name: Test
        run: yarn test:ci

      - uses: codecov/codecov-action@v1
