name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip:ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          GIT_AUTHOR_NAME: 'dotkom-build'
          GIT_COMMITTER_NAME: 'dotkom-build'
          GIT_AUTHOR_EMAIL: dotkom@online.ntnu.no
          GIT_COMMITTER_EMAIL: dotkom@online.ntnu.no
